[project]
name = "uni-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "falsity", email = "1305543690@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "deepagents>=0.3.6",
    "tavily-python>=0.7.19",
    "python-dotenv>=1.0.0",
    "langchain-openai>=1.1.7",
    "markdownify>=1.2.2",
    "langchain-mcp-adapters>=0.2.1",
    "langgraph-checkpoint-postgres>=3.0.3",
    "psycopg[binary,pool]>=3.2.0",
]

[project.scripts]
uni-agent = "uni_agent:main"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"
